// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (username, password_hash) VALUES ($1, $2) RETURNING id, username, password_hash, disabled, created_at, last_login
`

type CreateAdminUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Username, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO admin_sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3) RETURNING id, user_id, token_hash, created_at, expires_at, last_seen
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteAdminUser = `-- name: DeleteAdminUser :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdminUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminUser, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM admin_sessions WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM admin_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM admin_sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, username, password_hash, disabled, created_at, last_login FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminUser(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUser, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, disabled, created_at, last_login FROM admin_users WHERE username = $1
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.expires_at, u.username, u.disabled
FROM admin_sessions s JOIN admin_users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Username  string             `json:"username"`
	Disabled  bool               `json:"disabled"`
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Username,
		&i.Disabled,
	)
	return i, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, username, disabled, created_at, last_login FROM admin_users ORDER BY username
`

type ListAdminUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Disabled  bool               `json:"disabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminUsersRow{}
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Disabled,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdminDisabled = `-- name: SetAdminDisabled :exec
UPDATE admin_users SET disabled = $2 WHERE id = $1
`

type SetAdminDisabledParams struct {
	ID       uuid.UUID `json:"id"`
	Disabled bool      `json:"disabled"`
}

func (q *Queries) SetAdminDisabled(ctx context.Context, arg SetAdminDisabledParams) error {
	_, err := q.db.Exec(ctx, setAdminDisabled, arg.ID, arg.Disabled)
	return err
}

const touchAdminLogin = `-- name: TouchAdminLogin :exec
UPDATE admin_users SET last_login = now() WHERE id = $1
`

func (q *Queries) TouchAdminLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminLogin, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE admin_sessions SET last_seen = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users SET password_hash = $2 WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}
