// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bounce.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addSuppression = `-- name: AddSuppression :one
INSERT INTO suppressions (domain_id, address, reason)
VALUES ($1, $2, $3)
ON CONFLICT (domain_id, address) DO UPDATE SET reason = EXCLUDED.reason
RETURNING id, domain_id, address, reason, created_at
`

type AddSuppressionParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Address  string    `json:"address"`
	Reason   *string   `json:"reason"`
}

func (q *Queries) AddSuppression(ctx context.Context, arg AddSuppressionParams) (Suppression, error) {
	row := q.db.QueryRow(ctx, addSuppression, arg.DomainID, arg.Address, arg.Reason)
	var i Suppression
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Address,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const failJobByRcpt = `-- name: FailJobByRcpt :exec
UPDATE delivery_jobs SET status = 'failed', last_code = $3, last_response = $4, locked_by = NULL
WHERE message_id = $1 AND rcpt = $2
`

type FailJobByRcptParams struct {
	MessageID    uuid.UUID `json:"message_id"`
	Rcpt         string    `json:"rcpt"`
	LastCode     *int32    `json:"last_code"`
	LastResponse *string   `json:"last_response"`
}

func (q *Queries) FailJobByRcpt(ctx context.Context, arg FailJobByRcptParams) error {
	_, err := q.db.Exec(ctx, failJobByRcpt,
		arg.MessageID,
		arg.Rcpt,
		arg.LastCode,
		arg.LastResponse,
	)
	return err
}

const insertBounceEvent = `-- name: InsertBounceEvent :one
INSERT INTO bounce_events (message_id, rcpt, type, dsn_code, raw_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, rcpt, type, dsn_code, raw_ref, created_at
`

type InsertBounceEventParams struct {
	MessageID *uuid.UUID `json:"message_id"`
	Rcpt      *string    `json:"rcpt"`
	Type      string     `json:"type"`
	DsnCode   *string    `json:"dsn_code"`
	RawRef    *string    `json:"raw_ref"`
}

func (q *Queries) InsertBounceEvent(ctx context.Context, arg InsertBounceEventParams) (BounceEvent, error) {
	row := q.db.QueryRow(ctx, insertBounceEvent,
		arg.MessageID,
		arg.Rcpt,
		arg.Type,
		arg.DsnCode,
		arg.RawRef,
	)
	var i BounceEvent
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Rcpt,
		&i.Type,
		&i.DsnCode,
		&i.RawRef,
		&i.CreatedAt,
	)
	return i, err
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (SELECT 1 FROM suppressions WHERE domain_id = $1 AND lower(address) = lower($2)) AS suppressed
`

type IsSuppressedParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Address  string    `json:"address"`
}

func (q *Queries) IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, arg.DomainID, arg.Address)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const listBounceEvents = `-- name: ListBounceEvents :many
SELECT id, message_id, rcpt, type, dsn_code, raw_ref, created_at FROM bounce_events WHERE message_id = $1 ORDER BY created_at
`

func (q *Queries) ListBounceEvents(ctx context.Context, messageID *uuid.UUID) ([]BounceEvent, error) {
	rows, err := q.db.Query(ctx, listBounceEvents, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BounceEvent{}
	for rows.Next() {
		var i BounceEvent
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Rcpt,
			&i.Type,
			&i.DsnCode,
			&i.RawRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT id, domain_id, address, reason, created_at FROM suppressions WHERE domain_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSuppressionsParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]Suppression, error) {
	rows, err := q.db.Query(ctx, listSuppressions, arg.DomainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suppression{}
	for rows.Next() {
		var i Suppression
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Address,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSuppression = `-- name: RemoveSuppression :exec
DELETE FROM suppressions WHERE domain_id = $1 AND lower(address) = lower($2)
`

type RemoveSuppressionParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Address  string    `json:"address"`
}

func (q *Queries) RemoveSuppression(ctx context.Context, arg RemoveSuppressionParams) error {
	_, err := q.db.Exec(ctx, removeSuppression, arg.DomainID, arg.Address)
	return err
}
