// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (domain_id, username, secret_hash, restrictions)
VALUES ($1, $2, $3, $4)
RETURNING id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at
`

type CreateCredentialParams struct {
	DomainID     uuid.UUID `json:"domain_id"`
	Username     string    `json:"username"`
	SecretHash   string    `json:"secret_hash"`
	Restrictions []byte    `json:"restrictions"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.DomainID,
		arg.Username,
		arg.SecretHash,
		arg.Restrictions,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Username,
		&i.SecretHash,
		&i.Restrictions,
		&i.Status,
		&i.LastUsed,
		&i.FailedAuthCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const credentialCoversDomain = `-- name: CredentialCoversDomain :one
SELECT (
    EXISTS (SELECT 1 FROM credentials c WHERE c.id = $1 AND c.domain_id = $2)
    OR
    EXISTS (SELECT 1 FROM credential_domains cd WHERE cd.credential_id = $1 AND cd.domain_id = $2)
) AS covers
`

type CredentialCoversDomainParams struct {
	ID       uuid.UUID `json:"id"`
	DomainID uuid.UUID `json:"domain_id"`
}

func (q *Queries) CredentialCoversDomain(ctx context.Context, arg CredentialCoversDomainParams) (*bool, error) {
	row := q.db.QueryRow(ctx, credentialCoversDomain, arg.ID, arg.DomainID)
	var covers *bool
	err := row.Scan(&covers)
	return covers, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredential, id)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredential(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Username,
		&i.SecretHash,
		&i.Restrictions,
		&i.Status,
		&i.LastUsed,
		&i.FailedAuthCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByUsername = `-- name: GetCredentialByUsername :one
SELECT id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at FROM credentials WHERE username = $1
`

func (q *Queries) GetCredentialByUsername(ctx context.Context, username string) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUsername, username)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Username,
		&i.SecretHash,
		&i.Restrictions,
		&i.Status,
		&i.LastUsed,
		&i.FailedAuthCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantCredentialDomain = `-- name: GrantCredentialDomain :exec
INSERT INTO credential_domains (credential_id, domain_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantCredentialDomainParams struct {
	CredentialID uuid.UUID `json:"credential_id"`
	DomainID     uuid.UUID `json:"domain_id"`
}

func (q *Queries) GrantCredentialDomain(ctx context.Context, arg GrantCredentialDomainParams) error {
	_, err := q.db.Exec(ctx, grantCredentialDomain, arg.CredentialID, arg.DomainID)
	return err
}

const listCredentialDomains = `-- name: ListCredentialDomains :many
SELECT d.id, d.name, d.status, d.receiving, d.verify_token, d.bounce_subdomain, d.forward_bounces, d.sending_paused, d.created_at, d.updated_at, d.delivery_max_age_seconds FROM domains d
JOIN credential_domains cd ON cd.domain_id = d.id
WHERE cd.credential_id = $1
`

func (q *Queries) ListCredentialDomains(ctx context.Context, credentialID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listCredentialDomains, credentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Receiving,
			&i.VerifyToken,
			&i.BounceSubdomain,
			&i.ForwardBounces,
			&i.SendingPaused,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryMaxAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByDomain = `-- name: ListCredentialsByDomain :many
SELECT id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at FROM credentials
WHERE domain_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCredentialsByDomainParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCredentialsByDomain(ctx context.Context, arg ListCredentialsByDomainParams) ([]Credential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByDomain, arg.DomainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Username,
			&i.SecretHash,
			&i.Restrictions,
			&i.Status,
			&i.LastUsed,
			&i.FailedAuthCount,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailedAuth = `-- name: RecordFailedAuth :one
UPDATE credentials
SET failed_auth_count = failed_auth_count + 1
WHERE id = $1
RETURNING failed_auth_count
`

func (q *Queries) RecordFailedAuth(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordFailedAuth, id)
	var failed_auth_count int32
	err := row.Scan(&failed_auth_count)
	return failed_auth_count, err
}

const revokeCredentialDomain = `-- name: RevokeCredentialDomain :exec
DELETE FROM credential_domains WHERE credential_id = $1 AND domain_id = $2
`

type RevokeCredentialDomainParams struct {
	CredentialID uuid.UUID `json:"credential_id"`
	DomainID     uuid.UUID `json:"domain_id"`
}

func (q *Queries) RevokeCredentialDomain(ctx context.Context, arg RevokeCredentialDomainParams) error {
	_, err := q.db.Exec(ctx, revokeCredentialDomain, arg.CredentialID, arg.DomainID)
	return err
}

const setCredentialLock = `-- name: SetCredentialLock :exec
UPDATE credentials SET locked_until = $2 WHERE id = $1
`

type SetCredentialLockParams struct {
	ID          uuid.UUID          `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) SetCredentialLock(ctx context.Context, arg SetCredentialLockParams) error {
	_, err := q.db.Exec(ctx, setCredentialLock, arg.ID, arg.LockedUntil)
	return err
}

const touchCredentialLastUsed = `-- name: TouchCredentialLastUsed :exec
UPDATE credentials SET last_used = now(), failed_auth_count = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) TouchCredentialLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCredentialLastUsed, id)
	return err
}

const updateCredentialRestrictions = `-- name: UpdateCredentialRestrictions :one
UPDATE credentials SET restrictions = $2 WHERE id = $1 RETURNING id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at
`

type UpdateCredentialRestrictionsParams struct {
	ID           uuid.UUID `json:"id"`
	Restrictions []byte    `json:"restrictions"`
}

func (q *Queries) UpdateCredentialRestrictions(ctx context.Context, arg UpdateCredentialRestrictionsParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredentialRestrictions, arg.ID, arg.Restrictions)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Username,
		&i.SecretHash,
		&i.Restrictions,
		&i.Status,
		&i.LastUsed,
		&i.FailedAuthCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredentialStatus = `-- name: UpdateCredentialStatus :one
UPDATE credentials SET status = $2 WHERE id = $1 RETURNING id, domain_id, username, secret_hash, restrictions, status, last_used, failed_auth_count, locked_until, created_at, updated_at
`

type UpdateCredentialStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCredentialStatus(ctx context.Context, arg UpdateCredentialStatusParams) (Credential, error) {
	row := q.db.QueryRow(ctx, updateCredentialStatus, arg.ID, arg.Status)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Username,
		&i.SecretHash,
		&i.Restrictions,
		&i.Status,
		&i.LastUsed,
		&i.FailedAuthCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
