// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDeliveryJobs = `-- name: ClaimDeliveryJobs :many
UPDATE delivery_jobs SET
    status = 'in_progress',
    locked_at = now(),
    locked_by = $1,
    attempts = attempts + 1
WHERE id IN (
    SELECT id FROM delivery_jobs
    WHERE status IN ('queued', 'deferred') AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, message_id, rcpt, status, attempts, next_attempt_at, locked_at, locked_by, last_code, last_response, created_at, updated_at
`

type ClaimDeliveryJobsParams struct {
	LockedBy *string `json:"locked_by"`
	Limit    int32   `json:"limit"`
}

// Atomically claim due jobs with SKIP LOCKED so multiple workers never grab the
// same job. Increments attempts and marks in_progress.
func (q *Queries) ClaimDeliveryJobs(ctx context.Context, arg ClaimDeliveryJobsParams) ([]DeliveryJob, error) {
	rows, err := q.db.Query(ctx, claimDeliveryJobs, arg.LockedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryJob{}
	for rows.Next() {
		var i DeliveryJob
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Rcpt,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.LastCode,
			&i.LastResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deferJob = `-- name: DeferJob :exec
UPDATE delivery_jobs SET status = 'deferred', next_attempt_at = $2, last_code = $3, last_response = $4, locked_by = NULL WHERE id = $1
`

type DeferJobParams struct {
	ID            uuid.UUID          `json:"id"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastCode      *int32             `json:"last_code"`
	LastResponse  *string            `json:"last_response"`
}

func (q *Queries) DeferJob(ctx context.Context, arg DeferJobParams) error {
	_, err := q.db.Exec(ctx, deferJob,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastCode,
		arg.LastResponse,
	)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE delivery_jobs SET status = 'failed', last_code = $2, last_response = $3, locked_by = NULL WHERE id = $1
`

type FailJobParams struct {
	ID           uuid.UUID `json:"id"`
	LastCode     *int32    `json:"last_code"`
	LastResponse *string   `json:"last_response"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastCode, arg.LastResponse)
	return err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :exec
INSERT INTO delivery_attempts (
    message_id, rcpt, mx_host, finished_at, result, smtp_code, smtp_response, tls_version, tls_verified
) VALUES ($1, $2, $3, now(), $4, $5, $6, $7, $8)
`

type InsertDeliveryAttemptParams struct {
	MessageID    uuid.UUID `json:"message_id"`
	Rcpt         string    `json:"rcpt"`
	MxHost       *string   `json:"mx_host"`
	Result       string    `json:"result"`
	SmtpCode     *int32    `json:"smtp_code"`
	SmtpResponse *string   `json:"smtp_response"`
	TlsVersion   *string   `json:"tls_version"`
	TlsVerified  *bool     `json:"tls_verified"`
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryAttempt,
		arg.MessageID,
		arg.Rcpt,
		arg.MxHost,
		arg.Result,
		arg.SmtpCode,
		arg.SmtpResponse,
		arg.TlsVersion,
		arg.TlsVerified,
	)
	return err
}

const jobStatusCounts = `-- name: JobStatusCounts :one
SELECT
    count(*) FILTER (WHERE status = 'delivered')                              AS delivered,
    count(*) FILTER (WHERE status = 'failed')                                 AS failed,
    count(*) FILTER (WHERE status IN ('queued', 'in_progress', 'deferred'))   AS pending
FROM delivery_jobs WHERE message_id = $1
`

type JobStatusCountsRow struct {
	Delivered int64 `json:"delivered"`
	Failed    int64 `json:"failed"`
	Pending   int64 `json:"pending"`
}

func (q *Queries) JobStatusCounts(ctx context.Context, messageID uuid.UUID) (JobStatusCountsRow, error) {
	row := q.db.QueryRow(ctx, jobStatusCounts, messageID)
	var i JobStatusCountsRow
	err := row.Scan(&i.Delivered, &i.Failed, &i.Pending)
	return i, err
}

const listDeliveryAttempts = `-- name: ListDeliveryAttempts :many
SELECT id, message_id, rcpt, mx_host, started_at, finished_at, result, smtp_code, smtp_response, tls_version, tls_verified FROM delivery_attempts WHERE message_id = $1 ORDER BY started_at
`

func (q *Queries) ListDeliveryAttempts(ctx context.Context, messageID uuid.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, listDeliveryAttempts, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Rcpt,
			&i.MxHost,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Result,
			&i.SmtpCode,
			&i.SmtpResponse,
			&i.TlsVersion,
			&i.TlsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobDelivered = `-- name: MarkJobDelivered :exec
UPDATE delivery_jobs SET status = 'delivered', last_code = $2, last_response = $3, locked_by = NULL WHERE id = $1
`

type MarkJobDeliveredParams struct {
	ID           uuid.UUID `json:"id"`
	LastCode     *int32    `json:"last_code"`
	LastResponse *string   `json:"last_response"`
}

func (q *Queries) MarkJobDelivered(ctx context.Context, arg MarkJobDeliveredParams) error {
	_, err := q.db.Exec(ctx, markJobDelivered, arg.ID, arg.LastCode, arg.LastResponse)
	return err
}

const queueDepth = `-- name: QueueDepth :one
SELECT count(*) FROM delivery_jobs WHERE status IN ('queued', 'deferred')
`

func (q *Queries) QueueDepth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, queueDepth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const requeueStaleJobs = `-- name: RequeueStaleJobs :exec
UPDATE delivery_jobs SET status = 'queued', locked_by = NULL, locked_at = NULL
WHERE status = 'in_progress' AND locked_at < $1
`

// Recover jobs whose worker died mid-flight (locked but never completed).
func (q *Queries) RequeueStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, requeueStaleJobs, lockedAt)
	return err
}
