// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dkim.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveDKIMKey = `-- name: GetActiveDKIMKey :one
SELECT id, domain_id, selector, algorithm, private_key_enc, public_key, active, created_at FROM dkim_keys
WHERE domain_id = $1 AND active = true
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveDKIMKey(ctx context.Context, domainID uuid.UUID) (DkimKey, error) {
	row := q.db.QueryRow(ctx, getActiveDKIMKey, domainID)
	var i DkimKey
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Selector,
		&i.Algorithm,
		&i.PrivateKeyEnc,
		&i.PublicKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const insertDKIMKey = `-- name: InsertDKIMKey :one
INSERT INTO dkim_keys (domain_id, selector, algorithm, private_key_enc, public_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, domain_id, selector, algorithm, private_key_enc, public_key, active, created_at
`

type InsertDKIMKeyParams struct {
	DomainID      uuid.UUID `json:"domain_id"`
	Selector      string    `json:"selector"`
	Algorithm     string    `json:"algorithm"`
	PrivateKeyEnc []byte    `json:"private_key_enc"`
	PublicKey     string    `json:"public_key"`
}

func (q *Queries) InsertDKIMKey(ctx context.Context, arg InsertDKIMKeyParams) (DkimKey, error) {
	row := q.db.QueryRow(ctx, insertDKIMKey,
		arg.DomainID,
		arg.Selector,
		arg.Algorithm,
		arg.PrivateKeyEnc,
		arg.PublicKey,
	)
	var i DkimKey
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.Selector,
		&i.Algorithm,
		&i.PrivateKeyEnc,
		&i.PublicKey,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listDKIMKeys = `-- name: ListDKIMKeys :many
SELECT id, domain_id, selector, algorithm, public_key, active, created_at
FROM dkim_keys WHERE domain_id = $1 ORDER BY created_at DESC
`

type ListDKIMKeysRow struct {
	ID        uuid.UUID          `json:"id"`
	DomainID  uuid.UUID          `json:"domain_id"`
	Selector  string             `json:"selector"`
	Algorithm string             `json:"algorithm"`
	PublicKey string             `json:"public_key"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDKIMKeys(ctx context.Context, domainID uuid.UUID) ([]ListDKIMKeysRow, error) {
	rows, err := q.db.Query(ctx, listDKIMKeys, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDKIMKeysRow{}
	for rows.Next() {
		var i ListDKIMKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Selector,
			&i.Algorithm,
			&i.PublicKey,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
