// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dmarc.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dMARCSummary = `-- name: DMARCSummary :one
SELECT
  COALESCE(SUM(message_count), 0)::bigint AS total,
  COALESCE(SUM(message_count) FILTER (WHERE dkim_result = 'pass' OR spf_result = 'pass'), 0)::bigint AS passed,
  COALESCE(SUM(message_count) FILTER (WHERE dkim_result = 'pass'), 0)::bigint AS dkim_pass,
  COALESCE(SUM(message_count) FILTER (WHERE spf_result = 'pass'), 0)::bigint AS spf_pass,
  COALESCE(SUM(message_count) FILTER (WHERE disposition = 'quarantine'), 0)::bigint AS quarantined,
  COALESCE(SUM(message_count) FILTER (WHERE disposition = 'reject'), 0)::bigint AS rejected
FROM dmarc_report_rows
WHERE domain_id = $1 AND row_end >= $2
`

type DMARCSummaryParams struct {
	DomainID uuid.UUID          `json:"domain_id"`
	RowEnd   pgtype.Timestamptz `json:"row_end"`
}

type DMARCSummaryRow struct {
	Total       int64 `json:"total"`
	Passed      int64 `json:"passed"`
	DkimPass    int64 `json:"dkim_pass"`
	SpfPass     int64 `json:"spf_pass"`
	Quarantined int64 `json:"quarantined"`
	Rejected    int64 `json:"rejected"`
}

// Aggregate totals for a domain since a cutoff. DMARC "pass" = aligned DKIM OR
// aligned SPF passed.
func (q *Queries) DMARCSummary(ctx context.Context, arg DMARCSummaryParams) (DMARCSummaryRow, error) {
	row := q.db.QueryRow(ctx, dMARCSummary, arg.DomainID, arg.RowEnd)
	var i DMARCSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Passed,
		&i.DkimPass,
		&i.SpfPass,
		&i.Quarantined,
		&i.Rejected,
	)
	return i, err
}

const dMARCTopSources = `-- name: DMARCTopSources :many
SELECT source_ip,
  COALESCE(SUM(message_count), 0)::bigint AS total,
  COALESCE(SUM(message_count) FILTER (WHERE dkim_result = 'pass' OR spf_result = 'pass'), 0)::bigint AS passed
FROM dmarc_report_rows
WHERE domain_id = $1 AND row_end >= $2
GROUP BY source_ip
ORDER BY total DESC
LIMIT $3
`

type DMARCTopSourcesParams struct {
	DomainID uuid.UUID          `json:"domain_id"`
	RowEnd   pgtype.Timestamptz `json:"row_end"`
	Limit    int32              `json:"limit"`
}

type DMARCTopSourcesRow struct {
	SourceIp string `json:"source_ip"`
	Total    int64  `json:"total"`
	Passed   int64  `json:"passed"`
}

func (q *Queries) DMARCTopSources(ctx context.Context, arg DMARCTopSourcesParams) ([]DMARCTopSourcesRow, error) {
	rows, err := q.db.Query(ctx, dMARCTopSources, arg.DomainID, arg.RowEnd, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DMARCTopSourcesRow{}
	for rows.Next() {
		var i DMARCTopSourcesRow
		if err := rows.Scan(&i.SourceIp, &i.Total, &i.Passed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDMARCRow = `-- name: InsertDMARCRow :exec
INSERT INTO dmarc_report_rows
  (report_id, domain_id, source_ip, message_count, disposition, dkim_result, spf_result, header_from, row_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertDMARCRowParams struct {
	ReportID     uuid.UUID          `json:"report_id"`
	DomainID     uuid.UUID          `json:"domain_id"`
	SourceIp     string             `json:"source_ip"`
	MessageCount int32              `json:"message_count"`
	Disposition  string             `json:"disposition"`
	DkimResult   string             `json:"dkim_result"`
	SpfResult    string             `json:"spf_result"`
	HeaderFrom   *string            `json:"header_from"`
	RowEnd       pgtype.Timestamptz `json:"row_end"`
}

func (q *Queries) InsertDMARCRow(ctx context.Context, arg InsertDMARCRowParams) error {
	_, err := q.db.Exec(ctx, insertDMARCRow,
		arg.ReportID,
		arg.DomainID,
		arg.SourceIp,
		arg.MessageCount,
		arg.Disposition,
		arg.DkimResult,
		arg.SpfResult,
		arg.HeaderFrom,
		arg.RowEnd,
	)
	return err
}

const listDMARCReports = `-- name: ListDMARCReports :many
SELECT id, org_name, report_id, date_begin, date_end, policy_p, policy_pct, received_at,
  (SELECT COALESCE(SUM(message_count),0)::bigint FROM dmarc_report_rows r WHERE r.report_id = dmarc_reports.id) AS messages
FROM dmarc_reports
WHERE dmarc_reports.domain_id = $1
ORDER BY date_end DESC
LIMIT $2 OFFSET $3
`

type ListDMARCReportsParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListDMARCReportsRow struct {
	ID         uuid.UUID          `json:"id"`
	OrgName    string             `json:"org_name"`
	ReportID   string             `json:"report_id"`
	DateBegin  pgtype.Timestamptz `json:"date_begin"`
	DateEnd    pgtype.Timestamptz `json:"date_end"`
	PolicyP    *string            `json:"policy_p"`
	PolicyPct  *int32             `json:"policy_pct"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	Messages   int64              `json:"messages"`
}

func (q *Queries) ListDMARCReports(ctx context.Context, arg ListDMARCReportsParams) ([]ListDMARCReportsRow, error) {
	rows, err := q.db.Query(ctx, listDMARCReports, arg.DomainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMARCReportsRow{}
	for rows.Next() {
		var i ListDMARCReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgName,
			&i.ReportID,
			&i.DateBegin,
			&i.DateEnd,
			&i.PolicyP,
			&i.PolicyPct,
			&i.ReceivedAt,
			&i.Messages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDMARCReport = `-- name: UpsertDMARCReport :one
INSERT INTO dmarc_reports (domain_id, org_name, report_id, date_begin, date_end, policy_p, policy_pct, raw_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, org_name, report_id) DO UPDATE SET org_name = EXCLUDED.org_name
RETURNING id, (xmax = 0) AS inserted
`

type UpsertDMARCReportParams struct {
	DomainID  uuid.UUID          `json:"domain_id"`
	OrgName   string             `json:"org_name"`
	ReportID  string             `json:"report_id"`
	DateBegin pgtype.Timestamptz `json:"date_begin"`
	DateEnd   pgtype.Timestamptz `json:"date_end"`
	PolicyP   *string            `json:"policy_p"`
	PolicyPct *int32             `json:"policy_pct"`
	RawRef    *string            `json:"raw_ref"`
}

type UpsertDMARCReportRow struct {
	ID       uuid.UUID `json:"id"`
	Inserted bool      `json:"inserted"`
}

// Idempotent per (domain, org, report_id). Returns (id, inserted?) — xmax=0
// means a fresh insert so the caller only adds rows for new reports.
func (q *Queries) UpsertDMARCReport(ctx context.Context, arg UpsertDMARCReportParams) (UpsertDMARCReportRow, error) {
	row := q.db.QueryRow(ctx, upsertDMARCReport,
		arg.DomainID,
		arg.OrgName,
		arg.ReportID,
		arg.DateBegin,
		arg.DateEnd,
		arg.PolicyP,
		arg.PolicyPct,
		arg.RawRef,
	)
	var i UpsertDMARCReportRow
	err := row.Scan(&i.ID, &i.Inserted)
	return i, err
}
