// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns_records.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteDNSRecords = `-- name: DeleteDNSRecords :exec
DELETE FROM dns_records WHERE domain_id = $1
`

func (q *Queries) DeleteDNSRecords(ctx context.Context, domainID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDNSRecords, domainID)
	return err
}

const listDNSRecords = `-- name: ListDNSRecords :many
SELECT id, domain_id, purpose, type, name, expected_value, observed_value, last_checked, last_result, detail FROM dns_records WHERE domain_id = $1 ORDER BY purpose
`

func (q *Queries) ListDNSRecords(ctx context.Context, domainID uuid.UUID) ([]DnsRecord, error) {
	rows, err := q.db.Query(ctx, listDNSRecords, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsRecord{}
	for rows.Next() {
		var i DnsRecord
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.Purpose,
			&i.Type,
			&i.Name,
			&i.ExpectedValue,
			&i.ObservedValue,
			&i.LastChecked,
			&i.LastResult,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDNSRecordResult = `-- name: UpdateDNSRecordResult :exec
UPDATE dns_records
SET observed_value = $3, last_result = $4, detail = $5, last_checked = now()
WHERE domain_id = $1 AND purpose = $2
`

type UpdateDNSRecordResultParams struct {
	DomainID      uuid.UUID `json:"domain_id"`
	Purpose       string    `json:"purpose"`
	ObservedValue *string   `json:"observed_value"`
	LastResult    string    `json:"last_result"`
	Detail        *string   `json:"detail"`
}

func (q *Queries) UpdateDNSRecordResult(ctx context.Context, arg UpdateDNSRecordResultParams) error {
	_, err := q.db.Exec(ctx, updateDNSRecordResult,
		arg.DomainID,
		arg.Purpose,
		arg.ObservedValue,
		arg.LastResult,
		arg.Detail,
	)
	return err
}

const upsertDNSRecord = `-- name: UpsertDNSRecord :exec
INSERT INTO dns_records (domain_id, purpose, type, name, expected_value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (domain_id, purpose)
DO UPDATE SET type = EXCLUDED.type, name = EXCLUDED.name, expected_value = EXCLUDED.expected_value
`

type UpsertDNSRecordParams struct {
	DomainID      uuid.UUID `json:"domain_id"`
	Purpose       string    `json:"purpose"`
	Type          string    `json:"type"`
	Name          string    `json:"name"`
	ExpectedValue string    `json:"expected_value"`
}

func (q *Queries) UpsertDNSRecord(ctx context.Context, arg UpsertDNSRecordParams) error {
	_, err := q.db.Exec(ctx, upsertDNSRecord,
		arg.DomainID,
		arg.Purpose,
		arg.Type,
		arg.Name,
		arg.ExpectedValue,
	)
	return err
}
