// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countDomains = `-- name: CountDomains :one
SELECT count(*) FROM domains
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (name, receiving, verify_token, bounce_subdomain)
VALUES ($1, $2, $3, $4)
RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type CreateDomainParams struct {
	Name            string `json:"name"`
	Receiving       bool   `json:"receiving"`
	VerifyToken     string `json:"verify_token"`
	BounceSubdomain string `json:"bounce_subdomain"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.Name,
		arg.Receiving,
		arg.VerifyToken,
		arg.BounceSubdomain,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDomain, id)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds FROM domains WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const getDomainByName = `-- name: GetDomainByName :one
SELECT id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds FROM domains WHERE name = $1
`

func (q *Queries) GetDomainByName(ctx context.Context, name string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByName, name)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const getDomainDeliveryMaxAge = `-- name: GetDomainDeliveryMaxAge :one
SELECT delivery_max_age_seconds FROM domains WHERE id = $1
`

func (q *Queries) GetDomainDeliveryMaxAge(ctx context.Context, id uuid.UUID) (*int32, error) {
	row := q.db.QueryRow(ctx, getDomainDeliveryMaxAge, id)
	var delivery_max_age_seconds *int32
	err := row.Scan(&delivery_max_age_seconds)
	return delivery_max_age_seconds, err
}

const listActiveDomains = `-- name: ListActiveDomains :many
SELECT id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds FROM domains WHERE status IN ('active','degraded')
`

func (q *Queries) ListActiveDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listActiveDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Receiving,
			&i.VerifyToken,
			&i.BounceSubdomain,
			&i.ForwardBounces,
			&i.SendingPaused,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryMaxAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds FROM domains
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Receiving,
			&i.VerifyToken,
			&i.BounceSubdomain,
			&i.ForwardBounces,
			&i.SendingPaused,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeliveryMaxAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDomainDeliveryMaxAge = `-- name: SetDomainDeliveryMaxAge :one
UPDATE domains SET delivery_max_age_seconds = $2 WHERE id = $1 RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type SetDomainDeliveryMaxAgeParams struct {
	ID                    uuid.UUID `json:"id"`
	DeliveryMaxAgeSeconds *int32    `json:"delivery_max_age_seconds"`
}

// $2 NULL clears the override (fall back to the global default).
func (q *Queries) SetDomainDeliveryMaxAge(ctx context.Context, arg SetDomainDeliveryMaxAgeParams) (Domain, error) {
	row := q.db.QueryRow(ctx, setDomainDeliveryMaxAge, arg.ID, arg.DeliveryMaxAgeSeconds)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const setDomainForwardBounces = `-- name: SetDomainForwardBounces :one
UPDATE domains SET forward_bounces = $2 WHERE id = $1 RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type SetDomainForwardBouncesParams struct {
	ID             uuid.UUID `json:"id"`
	ForwardBounces bool      `json:"forward_bounces"`
}

func (q *Queries) SetDomainForwardBounces(ctx context.Context, arg SetDomainForwardBouncesParams) (Domain, error) {
	row := q.db.QueryRow(ctx, setDomainForwardBounces, arg.ID, arg.ForwardBounces)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const setDomainReceiving = `-- name: SetDomainReceiving :one
UPDATE domains SET receiving = $2 WHERE id = $1 RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type SetDomainReceivingParams struct {
	ID        uuid.UUID `json:"id"`
	Receiving bool      `json:"receiving"`
}

func (q *Queries) SetDomainReceiving(ctx context.Context, arg SetDomainReceivingParams) (Domain, error) {
	row := q.db.QueryRow(ctx, setDomainReceiving, arg.ID, arg.Receiving)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const setDomainSendingPaused = `-- name: SetDomainSendingPaused :one
UPDATE domains SET sending_paused = $2 WHERE id = $1 RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type SetDomainSendingPausedParams struct {
	ID            uuid.UUID `json:"id"`
	SendingPaused bool      `json:"sending_paused"`
}

func (q *Queries) SetDomainSendingPaused(ctx context.Context, arg SetDomainSendingPausedParams) (Domain, error) {
	row := q.db.QueryRow(ctx, setDomainSendingPaused, arg.ID, arg.SendingPaused)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}

const updateDomainStatus = `-- name: UpdateDomainStatus :one
UPDATE domains SET status = $2 WHERE id = $1 RETURNING id, name, status, receiving, verify_token, bounce_subdomain, forward_bounces, sending_paused, created_at, updated_at, delivery_max_age_seconds
`

type UpdateDomainStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomainStatus, arg.ID, arg.Status)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Receiving,
		&i.VerifyToken,
		&i.BounceSubdomain,
		&i.ForwardBounces,
		&i.SendingPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeliveryMaxAgeSeconds,
	)
	return i, err
}
