// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (domain_id, credential_id, type, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, domain_id, credential_id, type, detail, created_at
`

type InsertEventParams struct {
	DomainID     *uuid.UUID `json:"domain_id"`
	CredentialID *uuid.UUID `json:"credential_id"`
	Type         string     `json:"type"`
	Detail       []byte     `json:"detail"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.DomainID,
		arg.CredentialID,
		arg.Type,
		arg.Detail,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.CredentialID,
		&i.Type,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, domain_id, credential_id, type, detail, created_at FROM events
WHERE ($3::uuid IS NULL OR domain_id = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
	DomainID *uuid.UUID `json:"domain_id"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset, arg.DomainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.CredentialID,
			&i.Type,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
