// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailboxes.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createMailbox = `-- name: CreateMailbox :one
INSERT INTO mailboxes (domain_id, local_part, webhook_url, webhook_secret_enc)
VALUES ($1, $2, $3, $4)
RETURNING id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at
`

type CreateMailboxParams struct {
	DomainID         uuid.UUID `json:"domain_id"`
	LocalPart        string    `json:"local_part"`
	WebhookUrl       string    `json:"webhook_url"`
	WebhookSecretEnc []byte    `json:"webhook_secret_enc"`
}

func (q *Queries) CreateMailbox(ctx context.Context, arg CreateMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, createMailbox,
		arg.DomainID,
		arg.LocalPart,
		arg.WebhookUrl,
		arg.WebhookSecretEnc,
	)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.LocalPart,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM mailboxes WHERE id = $1
`

func (q *Queries) DeleteMailbox(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMailbox, id)
	return err
}

const findMailbox = `-- name: FindMailbox :one
SELECT id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at FROM mailboxes
WHERE domain_id = $1 AND status = 'active' AND local_part IN (lower($2), '*')
ORDER BY (local_part = '*') ASC
LIMIT 1
`

type FindMailboxParams struct {
	DomainID  uuid.UUID `json:"domain_id"`
	LocalPart string    `json:"local_part"`
}

// Match an exact local part, falling back to a catch-all ('*'), among active mailboxes.
func (q *Queries) FindMailbox(ctx context.Context, arg FindMailboxParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, findMailbox, arg.DomainID, arg.LocalPart)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.LocalPart,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailbox = `-- name: GetMailbox :one
SELECT id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at FROM mailboxes WHERE id = $1
`

func (q *Queries) GetMailbox(ctx context.Context, id uuid.UUID) (Mailbox, error) {
	row := q.db.QueryRow(ctx, getMailbox, id)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.LocalPart,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMailboxesByDomain = `-- name: ListMailboxesByDomain :many
SELECT id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at FROM mailboxes WHERE domain_id = $1 ORDER BY local_part
`

func (q *Queries) ListMailboxesByDomain(ctx context.Context, domainID uuid.UUID) ([]Mailbox, error) {
	rows, err := q.db.Query(ctx, listMailboxesByDomain, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.LocalPart,
			&i.WebhookUrl,
			&i.WebhookSecretEnc,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMailboxStatus = `-- name: SetMailboxStatus :one
UPDATE mailboxes SET status = $2 WHERE id = $1 RETURNING id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at
`

type SetMailboxStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetMailboxStatus(ctx context.Context, arg SetMailboxStatusParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, setMailboxStatus, arg.ID, arg.Status)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.LocalPart,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMailboxWebhook = `-- name: UpdateMailboxWebhook :one
UPDATE mailboxes SET webhook_url = $2, webhook_secret_enc = $3 WHERE id = $1 RETURNING id, domain_id, local_part, webhook_url, webhook_secret_enc, status, created_at, updated_at
`

type UpdateMailboxWebhookParams struct {
	ID               uuid.UUID `json:"id"`
	WebhookUrl       string    `json:"webhook_url"`
	WebhookSecretEnc []byte    `json:"webhook_secret_enc"`
}

func (q *Queries) UpdateMailboxWebhook(ctx context.Context, arg UpdateMailboxWebhookParams) (Mailbox, error) {
	row := q.db.QueryRow(ctx, updateMailboxWebhook, arg.ID, arg.WebhookUrl, arg.WebhookSecretEnc)
	var i Mailbox
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.LocalPart,
		&i.WebhookUrl,
		&i.WebhookSecretEnc,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
