// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDegradedDomains = `-- name: CountDegradedDomains :one
SELECT count(*) FROM domains WHERE status = 'degraded'
`

func (q *Queries) CountDegradedDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDegradedDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentMessagesByCredential = `-- name: CountRecentMessagesByCredential :one
SELECT count(*) FROM messages
WHERE credential_id = $1 AND created_at > $2
`

type CountRecentMessagesByCredentialParams struct {
	CredentialID *uuid.UUID         `json:"credential_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountRecentMessagesByCredential(ctx context.Context, arg CountRecentMessagesByCredentialParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentMessagesByCredential, arg.CredentialID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagesByIDs = `-- name: DeleteMessagesByIDs :execrows
DELETE FROM messages WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteMessagesByIDs(ctx context.Context, ids []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagesByIDs, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueDeliveryJob = `-- name: EnqueueDeliveryJob :one
INSERT INTO delivery_jobs (message_id, rcpt)
VALUES ($1, $2)
RETURNING id, message_id, rcpt, status, attempts, next_attempt_at, locked_at, locked_by, last_code, last_response, created_at, updated_at
`

type EnqueueDeliveryJobParams struct {
	MessageID uuid.UUID `json:"message_id"`
	Rcpt      string    `json:"rcpt"`
}

func (q *Queries) EnqueueDeliveryJob(ctx context.Context, arg EnqueueDeliveryJobParams) (DeliveryJob, error) {
	row := q.db.QueryRow(ctx, enqueueDeliveryJob, arg.MessageID, arg.Rcpt)
	var i DeliveryJob
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Rcpt,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.LastCode,
		&i.LastResponse,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, direction, credential_id, domain_id, mail_from, header_from, rcpt_to, subject, size_bytes, dkim_selector, body_ref, verp_token, status, spf_result, dkim_result, queued_at, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Direction,
		&i.CredentialID,
		&i.DomainID,
		&i.MailFrom,
		&i.HeaderFrom,
		&i.RcptTo,
		&i.Subject,
		&i.SizeBytes,
		&i.DkimSelector,
		&i.BodyRef,
		&i.VerpToken,
		&i.Status,
		&i.SpfResult,
		&i.DkimResult,
		&i.QueuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    id, direction, credential_id, domain_id, mail_from, header_from, rcpt_to,
    subject, size_bytes, dkim_selector, body_ref, verp_token, status,
    spf_result, dkim_result
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15
)
RETURNING id, direction, credential_id, domain_id, mail_from, header_from, rcpt_to, subject, size_bytes, dkim_selector, body_ref, verp_token, status, spf_result, dkim_result, queued_at, created_at, updated_at
`

type InsertMessageParams struct {
	ID           uuid.UUID  `json:"id"`
	Direction    string     `json:"direction"`
	CredentialID *uuid.UUID `json:"credential_id"`
	DomainID     *uuid.UUID `json:"domain_id"`
	MailFrom     *string    `json:"mail_from"`
	HeaderFrom   *string    `json:"header_from"`
	RcptTo       []string   `json:"rcpt_to"`
	Subject      *string    `json:"subject"`
	SizeBytes    int64      `json:"size_bytes"`
	DkimSelector *string    `json:"dkim_selector"`
	BodyRef      *string    `json:"body_ref"`
	VerpToken    *string    `json:"verp_token"`
	Status       string     `json:"status"`
	SpfResult    *string    `json:"spf_result"`
	DkimResult   *string    `json:"dkim_result"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.Direction,
		arg.CredentialID,
		arg.DomainID,
		arg.MailFrom,
		arg.HeaderFrom,
		arg.RcptTo,
		arg.Subject,
		arg.SizeBytes,
		arg.DkimSelector,
		arg.BodyRef,
		arg.VerpToken,
		arg.Status,
		arg.SpfResult,
		arg.DkimResult,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Direction,
		&i.CredentialID,
		&i.DomainID,
		&i.MailFrom,
		&i.HeaderFrom,
		&i.RcptTo,
		&i.Subject,
		&i.SizeBytes,
		&i.DkimSelector,
		&i.BodyRef,
		&i.VerpToken,
		&i.Status,
		&i.SpfResult,
		&i.DkimResult,
		&i.QueuedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, direction, credential_id, domain_id, mail_from, header_from, rcpt_to, subject, size_bytes, dkim_selector, body_ref, verp_token, status, spf_result, dkim_result, queued_at, created_at, updated_at FROM messages
WHERE ($3::text IS NULL OR direction = $3)
  AND ($4::text IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR domain_id = $5)
  AND ($6::uuid IS NULL OR credential_id = $6)
  AND ($7::timestamptz IS NULL OR created_at >= $7)
  AND ($8::timestamptz IS NULL OR created_at <= $8)
  AND ($9::text IS NULL
       OR EXISTS (SELECT 1 FROM unnest(rcpt_to) AS r WHERE r ILIKE $9))
  AND ($10::text IS NULL OR header_from ILIKE $10)
  AND ($11::text IS NULL OR subject ILIKE $11)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMessagesParams struct {
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
	Direction    *string            `json:"direction"`
	Status       *string            `json:"status"`
	DomainID     *uuid.UUID         `json:"domain_id"`
	CredentialID *uuid.UUID         `json:"credential_id"`
	After        pgtype.Timestamptz `json:"after"`
	Before       pgtype.Timestamptz `json:"before"`
	RcptLike     *string            `json:"rcpt_like"`
	FromLike     *string            `json:"from_like"`
	SubjectLike  *string            `json:"subject_like"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.Limit,
		arg.Offset,
		arg.Direction,
		arg.Status,
		arg.DomainID,
		arg.CredentialID,
		arg.After,
		arg.Before,
		arg.RcptLike,
		arg.FromLike,
		arg.SubjectLike,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Direction,
			&i.CredentialID,
			&i.DomainID,
			&i.MailFrom,
			&i.HeaderFrom,
			&i.RcptTo,
			&i.Subject,
			&i.SizeBytes,
			&i.DkimSelector,
			&i.BodyRef,
			&i.VerpToken,
			&i.Status,
			&i.SpfResult,
			&i.DkimResult,
			&i.QueuedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageStatusCounts = `-- name: MessageStatusCounts :many
SELECT status, count(*)::bigint AS n FROM messages
WHERE direction = 'outbound' AND created_at > $1
GROUP BY status
`

type MessageStatusCountsRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) MessageStatusCounts(ctx context.Context, createdAt pgtype.Timestamptz) ([]MessageStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, messageStatusCounts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageStatusCountsRow{}
	for rows.Next() {
		var i MessageStatusCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesBeyondCount = `-- name: MessagesBeyondCount :many
SELECT id, body_ref FROM messages
ORDER BY created_at DESC
OFFSET $1
LIMIT $2
`

type MessagesBeyondCountParams struct {
	Keep int32 `json:"keep"`
	Lim  int32 `json:"lim"`
}

type MessagesBeyondCountRow struct {
	ID      uuid.UUID `json:"id"`
	BodyRef *string   `json:"body_ref"`
}

// Retention (count mode): rows to delete = everything past the newest `keep`.
func (q *Queries) MessagesBeyondCount(ctx context.Context, arg MessagesBeyondCountParams) ([]MessagesBeyondCountRow, error) {
	rows, err := q.db.Query(ctx, messagesBeyondCount, arg.Keep, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagesBeyondCountRow{}
	for rows.Next() {
		var i MessagesBeyondCountRow
		if err := rows.Scan(&i.ID, &i.BodyRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesOlderThan = `-- name: MessagesOlderThan :many
SELECT id, body_ref FROM messages
WHERE created_at < $1
ORDER BY created_at
LIMIT $2
`

type MessagesOlderThanParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type MessagesOlderThanRow struct {
	ID      uuid.UUID `json:"id"`
	BodyRef *string   `json:"body_ref"`
}

// Retention (age mode): message rows + their body refs older than the cutoff.
func (q *Queries) MessagesOlderThan(ctx context.Context, arg MessagesOlderThanParams) ([]MessagesOlderThanRow, error) {
	rows, err := q.db.Query(ctx, messagesOlderThan, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagesOlderThanRow{}
	for rows.Next() {
		var i MessagesOlderThanRow
		if err := rows.Scan(&i.ID, &i.BodyRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageStatus = `-- name: SetMessageStatus :exec
UPDATE messages SET status = $2 WHERE id = $1
`

type SetMessageStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) error {
	_, err := q.db.Exec(ctx, setMessageStatus, arg.ID, arg.Status)
	return err
}
