// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type AdminUser struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Disabled     bool               `json:"disabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
}

type ApiToken struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AppSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BounceEvent struct {
	ID        uuid.UUID          `json:"id"`
	MessageID *uuid.UUID         `json:"message_id"`
	Rcpt      *string            `json:"rcpt"`
	Type      string             `json:"type"`
	DsnCode   *string            `json:"dsn_code"`
	RawRef    *string            `json:"raw_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Credential struct {
	ID              uuid.UUID          `json:"id"`
	DomainID        uuid.UUID          `json:"domain_id"`
	Username        string             `json:"username"`
	SecretHash      string             `json:"secret_hash"`
	Restrictions    []byte             `json:"restrictions"`
	Status          string             `json:"status"`
	LastUsed        pgtype.Timestamptz `json:"last_used"`
	FailedAuthCount int32              `json:"failed_auth_count"`
	LockedUntil     pgtype.Timestamptz `json:"locked_until"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CredentialDomain struct {
	CredentialID uuid.UUID `json:"credential_id"`
	DomainID     uuid.UUID `json:"domain_id"`
}

type DeliveryAttempt struct {
	ID           uuid.UUID          `json:"id"`
	MessageID    uuid.UUID          `json:"message_id"`
	Rcpt         string             `json:"rcpt"`
	MxHost       *string            `json:"mx_host"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Result       string             `json:"result"`
	SmtpCode     *int32             `json:"smtp_code"`
	SmtpResponse *string            `json:"smtp_response"`
	TlsVersion   *string            `json:"tls_version"`
	TlsVerified  *bool              `json:"tls_verified"`
}

type DeliveryJob struct {
	ID            uuid.UUID          `json:"id"`
	MessageID     uuid.UUID          `json:"message_id"`
	Rcpt          string             `json:"rcpt"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      *string            `json:"locked_by"`
	LastCode      *int32             `json:"last_code"`
	LastResponse  *string            `json:"last_response"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DkimKey struct {
	ID            uuid.UUID          `json:"id"`
	DomainID      uuid.UUID          `json:"domain_id"`
	Selector      string             `json:"selector"`
	Algorithm     string             `json:"algorithm"`
	PrivateKeyEnc []byte             `json:"private_key_enc"`
	PublicKey     string             `json:"public_key"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DmarcReport struct {
	ID         uuid.UUID          `json:"id"`
	DomainID   uuid.UUID          `json:"domain_id"`
	OrgName    string             `json:"org_name"`
	ReportID   string             `json:"report_id"`
	DateBegin  pgtype.Timestamptz `json:"date_begin"`
	DateEnd    pgtype.Timestamptz `json:"date_end"`
	PolicyP    *string            `json:"policy_p"`
	PolicyPct  *int32             `json:"policy_pct"`
	RawRef     *string            `json:"raw_ref"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type DmarcReportRow struct {
	ID           uuid.UUID          `json:"id"`
	ReportID     uuid.UUID          `json:"report_id"`
	DomainID     uuid.UUID          `json:"domain_id"`
	SourceIp     string             `json:"source_ip"`
	MessageCount int32              `json:"message_count"`
	Disposition  string             `json:"disposition"`
	DkimResult   string             `json:"dkim_result"`
	SpfResult    string             `json:"spf_result"`
	HeaderFrom   *string            `json:"header_from"`
	RowEnd       pgtype.Timestamptz `json:"row_end"`
}

type DnsRecord struct {
	ID            uuid.UUID          `json:"id"`
	DomainID      uuid.UUID          `json:"domain_id"`
	Purpose       string             `json:"purpose"`
	Type          string             `json:"type"`
	Name          string             `json:"name"`
	ExpectedValue string             `json:"expected_value"`
	ObservedValue *string            `json:"observed_value"`
	LastChecked   pgtype.Timestamptz `json:"last_checked"`
	LastResult    string             `json:"last_result"`
	Detail        *string            `json:"detail"`
}

type Domain struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	Receiving             bool               `json:"receiving"`
	VerifyToken           string             `json:"verify_token"`
	BounceSubdomain       string             `json:"bounce_subdomain"`
	ForwardBounces        bool               `json:"forward_bounces"`
	SendingPaused         bool               `json:"sending_paused"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeliveryMaxAgeSeconds *int32             `json:"delivery_max_age_seconds"`
}

type Event struct {
	ID           uuid.UUID          `json:"id"`
	DomainID     *uuid.UUID         `json:"domain_id"`
	CredentialID *uuid.UUID         `json:"credential_id"`
	Type         string             `json:"type"`
	Detail       []byte             `json:"detail"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Mailbox struct {
	ID               uuid.UUID          `json:"id"`
	DomainID         uuid.UUID          `json:"domain_id"`
	LocalPart        string             `json:"local_part"`
	WebhookUrl       string             `json:"webhook_url"`
	WebhookSecretEnc []byte             `json:"webhook_secret_enc"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID           uuid.UUID          `json:"id"`
	Direction    string             `json:"direction"`
	CredentialID *uuid.UUID         `json:"credential_id"`
	DomainID     *uuid.UUID         `json:"domain_id"`
	MailFrom     *string            `json:"mail_from"`
	HeaderFrom   *string            `json:"header_from"`
	RcptTo       []string           `json:"rcpt_to"`
	Subject      *string            `json:"subject"`
	SizeBytes    int64              `json:"size_bytes"`
	DkimSelector *string            `json:"dkim_selector"`
	BodyRef      *string            `json:"body_ref"`
	VerpToken    *string            `json:"verp_token"`
	Status       string             `json:"status"`
	SpfResult    *string            `json:"spf_result"`
	DkimResult   *string            `json:"dkim_result"`
	QueuedAt     pgtype.Timestamptz `json:"queued_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StatRollup struct {
	ID           uuid.UUID          `json:"id"`
	Bucket       pgtype.Timestamptz `json:"bucket"`
	DomainID     *uuid.UUID         `json:"domain_id"`
	CredentialID *uuid.UUID         `json:"credential_id"`
	Submitted    int64              `json:"submitted"`
	Delivered    int64              `json:"delivered"`
	Deferred     int64              `json:"deferred"`
	BouncedHard  int64              `json:"bounced_hard"`
	BouncedSoft  int64              `json:"bounced_soft"`
	Complaints   int64              `json:"complaints"`
}

type Suppression struct {
	ID        uuid.UUID          `json:"id"`
	DomainID  uuid.UUID          `json:"domain_id"`
	Address   string             `json:"address"`
	Reason    *string            `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TlsCert struct {
	ID        uuid.UUID          `json:"id"`
	DomainID  uuid.UUID          `json:"domain_id"`
	CertPem   string             `json:"cert_pem"`
	KeyEnc    []byte             `json:"key_enc"`
	Subjects  []string           `json:"subjects"`
	NotBefore pgtype.Timestamptz `json:"not_before"`
	NotAfter  pgtype.Timestamptz `json:"not_after"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID              uuid.UUID          `json:"id"`
	MailboxID       uuid.UUID          `json:"mailbox_id"`
	MessageID       uuid.UUID          `json:"message_id"`
	AttemptNo       int32              `json:"attempt_no"`
	StatusCode      *int32             `json:"status_code"`
	Result          string             `json:"result"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
	ResponseSnippet *string            `json:"response_snippet"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
