// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSuppression(ctx context.Context, arg AddSuppressionParams) (Suppression, error)
	// Atomically claim due jobs with SKIP LOCKED so multiple workers never grab the
	// same job. Increments attempts and marks in_progress.
	ClaimDeliveryJobs(ctx context.Context, arg ClaimDeliveryJobsParams) ([]DeliveryJob, error)
	ClaimWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	ClearMessageBodyRef(ctx context.Context, id uuid.UUID) error
	CountAdminUsers(ctx context.Context) (int64, error)
	// How many messages still reference a given body_ref (guards blob deletion).
	CountBodyRefUsers(ctx context.Context, bodyRef *string) (int64, error)
	CountDegradedDomains(ctx context.Context) (int64, error)
	CountDomains(ctx context.Context) (int64, error)
	CountEvents(ctx context.Context) (int64, error)
	CountRecentMessagesByCredential(ctx context.Context, arg CountRecentMessagesByCredentialParams) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateMailbox(ctx context.Context, arg CreateMailboxParams) (Mailbox, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AdminSession, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CredentialCoversDomain(ctx context.Context, arg CredentialCoversDomainParams) (*bool, error)
	// Windowed counts for a credential (since a cutoff timestamp).
	CredentialStats(ctx context.Context, arg CredentialStatsParams) (CredentialStatsRow, error)
	DeferJob(ctx context.Context, arg DeferJobParams) error
	DeleteAdminUser(ctx context.Context, id uuid.UUID) error
	DeleteCredential(ctx context.Context, id uuid.UUID) error
	DeleteDNSRecords(ctx context.Context, domainID uuid.UUID) error
	DeleteDomain(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMailbox(ctx context.Context, id uuid.UUID) error
	DeleteMessagesByIDs(ctx context.Context, ids []uuid.UUID) (int64, error)
	DeleteOldEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// Prune message metadata past the retention window. FK cascades remove the
	// associated delivery_jobs/attempts/bounce_events; stats rollups are separate.
	DeleteOldMessages(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteUserSessions(ctx context.Context, userID uuid.UUID) error
	DistinctActiveDomainIDs(ctx context.Context, createdAt pgtype.Timestamptz) ([]*uuid.UUID, error)
	DomainStats(ctx context.Context, arg DomainStatsParams) (DomainStatsRow, error)
	EnqueueDeliveryJob(ctx context.Context, arg EnqueueDeliveryJobParams) (DeliveryJob, error)
	// Inbound messages older than the cutoff whose body is no longer needed: no
	// webhook delivery is still pending (all succeeded, dead-lettered, or none).
	ExpiredInboundBodies(ctx context.Context, arg ExpiredInboundBodiesParams) ([]ExpiredInboundBodiesRow, error)
	// Retention: find/clear stored bodies past their per-direction TTL and prune
	// old metadata rows. Bodies are content-addressed, so callers must confirm no
	// other message still references a body_ref before deleting the blob file.
	// Outbound messages whose stored body is older than the cutoff.
	ExpiredOutboundBodies(ctx context.Context, arg ExpiredOutboundBodiesParams) ([]ExpiredOutboundBodiesRow, error)
	FailJob(ctx context.Context, arg FailJobParams) error
	FailJobByRcpt(ctx context.Context, arg FailJobByRcptParams) error
	// Match an exact local part, falling back to a catch-all ('*'), among active mailboxes.
	FindMailbox(ctx context.Context, arg FindMailboxParams) (Mailbox, error)
	GetActiveDKIMKey(ctx context.Context, domainID uuid.UUID) (DkimKey, error)
	GetAdminUser(ctx context.Context, id uuid.UUID) (AdminUser, error)
	GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error)
	GetCredential(ctx context.Context, id uuid.UUID) (Credential, error)
	GetCredentialByUsername(ctx context.Context, username string) (Credential, error)
	GetDomain(ctx context.Context, id uuid.UUID) (Domain, error)
	GetDomainByName(ctx context.Context, name string) (Domain, error)
	GetMailbox(ctx context.Context, id uuid.UUID) (Mailbox, error)
	GetMessage(ctx context.Context, id uuid.UUID) (Message, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error)
	GetSetting(ctx context.Context, key string) ([]byte, error)
	GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GrantCredentialDomain(ctx context.Context, arg GrantCredentialDomainParams) error
	InsertBounceEvent(ctx context.Context, arg InsertBounceEventParams) (BounceEvent, error)
	InsertDKIMKey(ctx context.Context, arg InsertDKIMKeyParams) (DkimKey, error)
	InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) error
	InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error)
	JobStatusCounts(ctx context.Context, messageID uuid.UUID) (JobStatusCountsRow, error)
	ListActiveDomains(ctx context.Context) ([]Domain, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListBounceEvents(ctx context.Context, messageID *uuid.UUID) ([]BounceEvent, error)
	ListCredentialDomains(ctx context.Context, credentialID uuid.UUID) ([]Domain, error)
	ListCredentialsByDomain(ctx context.Context, arg ListCredentialsByDomainParams) ([]Credential, error)
	ListDKIMKeys(ctx context.Context, domainID uuid.UUID) ([]ListDKIMKeysRow, error)
	ListDNSRecords(ctx context.Context, domainID uuid.UUID) ([]DnsRecord, error)
	ListDeliveryAttempts(ctx context.Context, messageID uuid.UUID) ([]DeliveryAttempt, error)
	ListDomains(ctx context.Context, arg ListDomainsParams) ([]Domain, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListMailboxesByDomain(ctx context.Context, domainID uuid.UUID) ([]Mailbox, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListStatRollups(ctx context.Context, arg ListStatRollupsParams) ([]ListStatRollupsRow, error)
	ListSuppressions(ctx context.Context, arg ListSuppressionsParams) ([]Suppression, error)
	ListWebhookDeliveriesByDomain(ctx context.Context, arg ListWebhookDeliveriesByDomainParams) ([]WebhookDelivery, error)
	MarkJobDelivered(ctx context.Context, arg MarkJobDeliveredParams) error
	MarkWebhookDeadLetter(ctx context.Context, arg MarkWebhookDeadLetterParams) error
	MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error
	MarkWebhookSuccess(ctx context.Context, arg MarkWebhookSuccessParams) error
	MessageStatusCounts(ctx context.Context, createdAt pgtype.Timestamptz) ([]MessageStatusCountsRow, error)
	// Retention (count mode): rows to delete = everything past the newest `keep`.
	MessagesBeyondCount(ctx context.Context, arg MessagesBeyondCountParams) ([]MessagesBeyondCountRow, error)
	// Retention (age mode): message rows + their body refs older than the cutoff.
	MessagesOlderThan(ctx context.Context, arg MessagesOlderThanParams) ([]MessagesOlderThanRow, error)
	QueueDepth(ctx context.Context) (int64, error)
	RecordFailedAuth(ctx context.Context, id uuid.UUID) (int32, error)
	RemoveSuppression(ctx context.Context, arg RemoveSuppressionParams) error
	// Recover jobs whose worker died mid-flight (locked but never completed).
	RequeueStaleJobs(ctx context.Context, lockedAt pgtype.Timestamptz) error
	RequeueWebhookDelivery(ctx context.Context, id uuid.UUID) error
	RevokeCredentialDomain(ctx context.Context, arg RevokeCredentialDomainParams) error
	SetAdminDisabled(ctx context.Context, arg SetAdminDisabledParams) error
	SetCredentialLock(ctx context.Context, arg SetCredentialLockParams) error
	SetDomainForwardBounces(ctx context.Context, arg SetDomainForwardBouncesParams) (Domain, error)
	SetDomainReceiving(ctx context.Context, arg SetDomainReceivingParams) (Domain, error)
	SetDomainSendingPaused(ctx context.Context, arg SetDomainSendingPausedParams) (Domain, error)
	SetMailboxStatus(ctx context.Context, arg SetMailboxStatusParams) (Mailbox, error)
	SetMessageStatus(ctx context.Context, arg SetMessageStatusParams) error
	TouchAdminLogin(ctx context.Context, id uuid.UUID) error
	TouchCredentialLastUsed(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	UpdateCredentialRestrictions(ctx context.Context, arg UpdateCredentialRestrictionsParams) (Credential, error)
	UpdateCredentialStatus(ctx context.Context, arg UpdateCredentialStatusParams) (Credential, error)
	UpdateDNSRecordResult(ctx context.Context, arg UpdateDNSRecordResultParams) error
	UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (Domain, error)
	UpdateMailboxWebhook(ctx context.Context, arg UpdateMailboxWebhookParams) (Mailbox, error)
	UpsertDNSRecord(ctx context.Context, arg UpsertDNSRecordParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	// Recompute one hourly per-domain bucket from source tables.
	UpsertStatRollup(ctx context.Context, arg UpsertStatRollupParams) error
}

var _ Querier = (*Queries)(nil)
