// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearMessageBodyRef = `-- name: ClearMessageBodyRef :exec
UPDATE messages SET body_ref = NULL WHERE id = $1
`

func (q *Queries) ClearMessageBodyRef(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMessageBodyRef, id)
	return err
}

const countBodyRefUsers = `-- name: CountBodyRefUsers :one
SELECT count(*) FROM messages WHERE body_ref = $1
`

// How many messages still reference a given body_ref (guards blob deletion).
func (q *Queries) CountBodyRefUsers(ctx context.Context, bodyRef *string) (int64, error) {
	row := q.db.QueryRow(ctx, countBodyRefUsers, bodyRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldEvents = `-- name: DeleteOldEvents :execrows
DELETE FROM events WHERE created_at < $1
`

func (q *Queries) DeleteOldEvents(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldEvents, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldMessages = `-- name: DeleteOldMessages :execrows
DELETE FROM messages WHERE created_at < $1
`

// Prune message metadata past the retention window. FK cascades remove the
// associated delivery_jobs/attempts/bounce_events; stats rollups are separate.
func (q *Queries) DeleteOldMessages(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMessages, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expiredInboundBodies = `-- name: ExpiredInboundBodies :many
SELECT m.id, m.body_ref FROM messages m
WHERE m.direction = 'inbound' AND m.body_ref IS NOT NULL AND m.created_at < $1
  AND NOT EXISTS (
    SELECT 1 FROM webhook_deliveries wd
    WHERE wd.message_id = m.id AND wd.result = 'pending'
  )
ORDER BY m.created_at
LIMIT $2
`

type ExpiredInboundBodiesParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ExpiredInboundBodiesRow struct {
	ID      uuid.UUID `json:"id"`
	BodyRef *string   `json:"body_ref"`
}

// Inbound messages older than the cutoff whose body is no longer needed: no
// webhook delivery is still pending (all succeeded, dead-lettered, or none).
func (q *Queries) ExpiredInboundBodies(ctx context.Context, arg ExpiredInboundBodiesParams) ([]ExpiredInboundBodiesRow, error) {
	rows, err := q.db.Query(ctx, expiredInboundBodies, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredInboundBodiesRow{}
	for rows.Next() {
		var i ExpiredInboundBodiesRow
		if err := rows.Scan(&i.ID, &i.BodyRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiredOutboundBodies = `-- name: ExpiredOutboundBodies :many

SELECT id, body_ref FROM messages
WHERE direction = 'outbound' AND body_ref IS NOT NULL AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ExpiredOutboundBodiesParams struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ExpiredOutboundBodiesRow struct {
	ID      uuid.UUID `json:"id"`
	BodyRef *string   `json:"body_ref"`
}

// Retention: find/clear stored bodies past their per-direction TTL and prune
// old metadata rows. Bodies are content-addressed, so callers must confirm no
// other message still references a body_ref before deleting the blob file.
// Outbound messages whose stored body is older than the cutoff.
func (q *Queries) ExpiredOutboundBodies(ctx context.Context, arg ExpiredOutboundBodiesParams) ([]ExpiredOutboundBodiesRow, error) {
	rows, err := q.db.Query(ctx, expiredOutboundBodies, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpiredOutboundBodiesRow{}
	for rows.Next() {
		var i ExpiredOutboundBodiesRow
		if err := rows.Scan(&i.ID, &i.BodyRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
