// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const credentialStats = `-- name: CredentialStats :one
WITH msgs AS (
    SELECT id FROM messages m WHERE m.credential_id = $1 AND m.created_at > $2
)
SELECT
    (SELECT count(*) FROM msgs)::bigint AS submitted,
    (SELECT count(DISTINCT (da.message_id, da.rcpt)) FROM delivery_attempts da
       WHERE da.message_id IN (SELECT id FROM msgs) AND da.result = 'delivered')::bigint AS delivered,
    (SELECT count(*) FROM delivery_jobs dj
       WHERE dj.message_id IN (SELECT id FROM msgs) AND dj.status = 'deferred')::bigint AS deferred,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'hard')::bigint AS bounced_hard,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'soft')::bigint AS bounced_soft,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'complaint')::bigint AS complaints
`

type CredentialStatsParams struct {
	CredentialID *uuid.UUID         `json:"credential_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CredentialStatsRow struct {
	Submitted   int64 `json:"submitted"`
	Delivered   int64 `json:"delivered"`
	Deferred    int64 `json:"deferred"`
	BouncedHard int64 `json:"bounced_hard"`
	BouncedSoft int64 `json:"bounced_soft"`
	Complaints  int64 `json:"complaints"`
}

// Windowed counts for a credential (since a cutoff timestamp).
func (q *Queries) CredentialStats(ctx context.Context, arg CredentialStatsParams) (CredentialStatsRow, error) {
	row := q.db.QueryRow(ctx, credentialStats, arg.CredentialID, arg.CreatedAt)
	var i CredentialStatsRow
	err := row.Scan(
		&i.Submitted,
		&i.Delivered,
		&i.Deferred,
		&i.BouncedHard,
		&i.BouncedSoft,
		&i.Complaints,
	)
	return i, err
}

const distinctActiveDomainIDs = `-- name: DistinctActiveDomainIDs :many
SELECT DISTINCT domain_id FROM messages WHERE domain_id IS NOT NULL AND created_at > $1
`

func (q *Queries) DistinctActiveDomainIDs(ctx context.Context, createdAt pgtype.Timestamptz) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, distinctActiveDomainIDs, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var domain_id *uuid.UUID
		if err := rows.Scan(&domain_id); err != nil {
			return nil, err
		}
		items = append(items, domain_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainStats = `-- name: DomainStats :one
WITH msgs AS (
    SELECT id FROM messages m WHERE m.domain_id = $1 AND m.direction = 'outbound' AND m.created_at > $2
)
SELECT
    (SELECT count(*) FROM msgs)::bigint AS submitted,
    (SELECT count(DISTINCT (da.message_id, da.rcpt)) FROM delivery_attempts da
       WHERE da.message_id IN (SELECT id FROM msgs) AND da.result = 'delivered')::bigint AS delivered,
    (SELECT count(*) FROM delivery_jobs dj
       WHERE dj.message_id IN (SELECT id FROM msgs) AND dj.status = 'deferred')::bigint AS deferred,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'hard')::bigint AS bounced_hard,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'soft')::bigint AS bounced_soft,
    (SELECT count(*) FROM bounce_events be
       WHERE be.message_id IN (SELECT id FROM msgs) AND be.type = 'complaint')::bigint AS complaints
`

type DomainStatsParams struct {
	DomainID  *uuid.UUID         `json:"domain_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DomainStatsRow struct {
	Submitted   int64 `json:"submitted"`
	Delivered   int64 `json:"delivered"`
	Deferred    int64 `json:"deferred"`
	BouncedHard int64 `json:"bounced_hard"`
	BouncedSoft int64 `json:"bounced_soft"`
	Complaints  int64 `json:"complaints"`
}

func (q *Queries) DomainStats(ctx context.Context, arg DomainStatsParams) (DomainStatsRow, error) {
	row := q.db.QueryRow(ctx, domainStats, arg.DomainID, arg.CreatedAt)
	var i DomainStatsRow
	err := row.Scan(
		&i.Submitted,
		&i.Delivered,
		&i.Deferred,
		&i.BouncedHard,
		&i.BouncedSoft,
		&i.Complaints,
	)
	return i, err
}

const listStatRollups = `-- name: ListStatRollups :many
SELECT bucket, submitted, delivered, deferred, bounced_hard, bounced_soft, complaints
FROM stat_rollups
WHERE domain_id = $1 AND credential_id IS NULL AND bucket >= $2
ORDER BY bucket
`

type ListStatRollupsParams struct {
	DomainID *uuid.UUID         `json:"domain_id"`
	Bucket   pgtype.Timestamptz `json:"bucket"`
}

type ListStatRollupsRow struct {
	Bucket      pgtype.Timestamptz `json:"bucket"`
	Submitted   int64              `json:"submitted"`
	Delivered   int64              `json:"delivered"`
	Deferred    int64              `json:"deferred"`
	BouncedHard int64              `json:"bounced_hard"`
	BouncedSoft int64              `json:"bounced_soft"`
	Complaints  int64              `json:"complaints"`
}

func (q *Queries) ListStatRollups(ctx context.Context, arg ListStatRollupsParams) ([]ListStatRollupsRow, error) {
	rows, err := q.db.Query(ctx, listStatRollups, arg.DomainID, arg.Bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatRollupsRow{}
	for rows.Next() {
		var i ListStatRollupsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Submitted,
			&i.Delivered,
			&i.Deferred,
			&i.BouncedHard,
			&i.BouncedSoft,
			&i.Complaints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStatRollup = `-- name: UpsertStatRollup :exec
INSERT INTO stat_rollups (bucket, domain_id, submitted, delivered, deferred, bounced_hard, bounced_soft, complaints)
SELECT
    $1::timestamptz AS bucket,
    $2::uuid AS domain_id,
    (SELECT count(*) FROM messages m WHERE m.domain_id = $2 AND m.direction = 'outbound'
        AND m.created_at >= $1 AND m.created_at < $1 + interval '1 hour'),
    (SELECT count(DISTINCT (da.message_id, da.rcpt)) FROM delivery_attempts da
        JOIN messages m ON m.id = da.message_id
        WHERE m.domain_id = $2 AND da.result = 'delivered'
        AND da.started_at >= $1 AND da.started_at < $1 + interval '1 hour'),
    (SELECT count(*) FROM delivery_attempts da
        JOIN messages m ON m.id = da.message_id
        WHERE m.domain_id = $2 AND da.result = 'deferred'
        AND da.started_at >= $1 AND da.started_at < $1 + interval '1 hour'),
    (SELECT count(*) FROM bounce_events be
        JOIN messages m ON m.id = be.message_id
        WHERE m.domain_id = $2 AND be.type = 'hard'
        AND be.created_at >= $1 AND be.created_at < $1 + interval '1 hour'),
    (SELECT count(*) FROM bounce_events be
        JOIN messages m ON m.id = be.message_id
        WHERE m.domain_id = $2 AND be.type = 'soft'
        AND be.created_at >= $1 AND be.created_at < $1 + interval '1 hour'),
    (SELECT count(*) FROM bounce_events be
        JOIN messages m ON m.id = be.message_id
        WHERE m.domain_id = $2 AND be.type = 'complaint'
        AND be.created_at >= $1 AND be.created_at < $1 + interval '1 hour')
ON CONFLICT (bucket, domain_id, credential_id) DO UPDATE SET
    submitted = EXCLUDED.submitted, delivered = EXCLUDED.delivered, deferred = EXCLUDED.deferred,
    bounced_hard = EXCLUDED.bounced_hard, bounced_soft = EXCLUDED.bounced_soft, complaints = EXCLUDED.complaints
`

type UpsertStatRollupParams struct {
	Bucket   pgtype.Timestamptz `json:"bucket"`
	DomainID uuid.UUID          `json:"domain_id"`
}

// Recompute one hourly per-domain bucket from source tables.
func (q *Queries) UpsertStatRollup(ctx context.Context, arg UpsertStatRollupParams) error {
	_, err := q.db.Exec(ctx, upsertStatRollup, arg.Bucket, arg.DomainID)
	return err
}
