// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tls.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDomainTLSCert = `-- name: DeleteDomainTLSCert :execrows
DELETE FROM tls_certs WHERE domain_id = $1
`

func (q *Queries) DeleteDomainTLSCert(ctx context.Context, domainID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDomainTLSCert, domainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDomainTLSCert = `-- name: GetDomainTLSCert :one
SELECT id, domain_id, cert_pem, key_enc, subjects, not_before, not_after, created_at, updated_at FROM tls_certs WHERE domain_id = $1
`

func (q *Queries) GetDomainTLSCert(ctx context.Context, domainID uuid.UUID) (TlsCert, error) {
	row := q.db.QueryRow(ctx, getDomainTLSCert, domainID)
	var i TlsCert
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.CertPem,
		&i.KeyEnc,
		&i.Subjects,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTLSCerts = `-- name: ListTLSCerts :many
SELECT id, domain_id, cert_pem, key_enc, subjects, not_before, not_after FROM tls_certs
`

type ListTLSCertsRow struct {
	ID        uuid.UUID          `json:"id"`
	DomainID  uuid.UUID          `json:"domain_id"`
	CertPem   string             `json:"cert_pem"`
	KeyEnc    []byte             `json:"key_enc"`
	Subjects  []string           `json:"subjects"`
	NotBefore pgtype.Timestamptz `json:"not_before"`
	NotAfter  pgtype.Timestamptz `json:"not_after"`
}

func (q *Queries) ListTLSCerts(ctx context.Context) ([]ListTLSCertsRow, error) {
	rows, err := q.db.Query(ctx, listTLSCerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTLSCertsRow{}
	for rows.Next() {
		var i ListTLSCertsRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainID,
			&i.CertPem,
			&i.KeyEnc,
			&i.Subjects,
			&i.NotBefore,
			&i.NotAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomainTLSCert = `-- name: UpsertDomainTLSCert :one
INSERT INTO tls_certs (domain_id, cert_pem, key_enc, subjects, not_before, not_after)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (domain_id) DO UPDATE SET
  cert_pem = EXCLUDED.cert_pem, key_enc = EXCLUDED.key_enc, subjects = EXCLUDED.subjects,
  not_before = EXCLUDED.not_before, not_after = EXCLUDED.not_after, updated_at = now()
RETURNING id, domain_id, cert_pem, key_enc, subjects, not_before, not_after, created_at, updated_at
`

type UpsertDomainTLSCertParams struct {
	DomainID  uuid.UUID          `json:"domain_id"`
	CertPem   string             `json:"cert_pem"`
	KeyEnc    []byte             `json:"key_enc"`
	Subjects  []string           `json:"subjects"`
	NotBefore pgtype.Timestamptz `json:"not_before"`
	NotAfter  pgtype.Timestamptz `json:"not_after"`
}

func (q *Queries) UpsertDomainTLSCert(ctx context.Context, arg UpsertDomainTLSCertParams) (TlsCert, error) {
	row := q.db.QueryRow(ctx, upsertDomainTLSCert,
		arg.DomainID,
		arg.CertPem,
		arg.KeyEnc,
		arg.Subjects,
		arg.NotBefore,
		arg.NotAfter,
	)
	var i TlsCert
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.CertPem,
		&i.KeyEnc,
		&i.Subjects,
		&i.NotBefore,
		&i.NotAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
