// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
UPDATE webhook_deliveries SET attempt_no = attempt_no + 1
WHERE id IN (
    SELECT id FROM webhook_deliveries
    WHERE result = 'pending' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, mailbox_id, message_id, attempt_no, status_code, result, next_attempt_at, response_snippet, created_at, updated_at
`

func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.MessageID,
			&i.AttemptNo,
			&i.StatusCode,
			&i.Result,
			&i.NextAttemptAt,
			&i.ResponseSnippet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (mailbox_id, message_id, next_attempt_at, result)
VALUES ($1, $2, now(), 'pending')
RETURNING id, mailbox_id, message_id, attempt_no, status_code, result, next_attempt_at, response_snippet, created_at, updated_at
`

type CreateWebhookDeliveryParams struct {
	MailboxID uuid.UUID `json:"mailbox_id"`
	MessageID uuid.UUID `json:"message_id"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery, arg.MailboxID, arg.MessageID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.MessageID,
		&i.AttemptNo,
		&i.StatusCode,
		&i.Result,
		&i.NextAttemptAt,
		&i.ResponseSnippet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, mailbox_id, message_id, attempt_no, status_code, result, next_attempt_at, response_snippet, created_at, updated_at FROM webhook_deliveries WHERE id = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MailboxID,
		&i.MessageID,
		&i.AttemptNo,
		&i.StatusCode,
		&i.Result,
		&i.NextAttemptAt,
		&i.ResponseSnippet,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveriesByDomain = `-- name: ListWebhookDeliveriesByDomain :many
SELECT wd.id, wd.mailbox_id, wd.message_id, wd.attempt_no, wd.status_code, wd.result, wd.next_attempt_at, wd.response_snippet, wd.created_at, wd.updated_at FROM webhook_deliveries wd
JOIN mailboxes m ON m.id = wd.mailbox_id
WHERE m.domain_id = $1
ORDER BY wd.created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesByDomainParams struct {
	DomainID uuid.UUID `json:"domain_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveriesByDomain(ctx context.Context, arg ListWebhookDeliveriesByDomainParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByDomain, arg.DomainID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.MessageID,
			&i.AttemptNo,
			&i.StatusCode,
			&i.Result,
			&i.NextAttemptAt,
			&i.ResponseSnippet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesByMessage = `-- name: ListWebhookDeliveriesByMessage :many
SELECT id, mailbox_id, message_id, attempt_no, status_code, result, next_attempt_at, response_snippet, created_at, updated_at FROM webhook_deliveries WHERE message_id = $1 ORDER BY attempt_no
`

func (q *Queries) ListWebhookDeliveriesByMessage(ctx context.Context, messageID uuid.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MailboxID,
			&i.MessageID,
			&i.AttemptNo,
			&i.StatusCode,
			&i.Result,
			&i.NextAttemptAt,
			&i.ResponseSnippet,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeadLetter = `-- name: MarkWebhookDeadLetter :exec
UPDATE webhook_deliveries SET result = 'dead_letter', status_code = $2, response_snippet = $3 WHERE id = $1
`

type MarkWebhookDeadLetterParams struct {
	ID              uuid.UUID `json:"id"`
	StatusCode      *int32    `json:"status_code"`
	ResponseSnippet *string   `json:"response_snippet"`
}

func (q *Queries) MarkWebhookDeadLetter(ctx context.Context, arg MarkWebhookDeadLetterParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeadLetter, arg.ID, arg.StatusCode, arg.ResponseSnippet)
	return err
}

const markWebhookRetry = `-- name: MarkWebhookRetry :exec
UPDATE webhook_deliveries SET result = 'pending', status_code = $2, response_snippet = $3, next_attempt_at = $4 WHERE id = $1
`

type MarkWebhookRetryParams struct {
	ID              uuid.UUID          `json:"id"`
	StatusCode      *int32             `json:"status_code"`
	ResponseSnippet *string            `json:"response_snippet"`
	NextAttemptAt   pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) MarkWebhookRetry(ctx context.Context, arg MarkWebhookRetryParams) error {
	_, err := q.db.Exec(ctx, markWebhookRetry,
		arg.ID,
		arg.StatusCode,
		arg.ResponseSnippet,
		arg.NextAttemptAt,
	)
	return err
}

const markWebhookSuccess = `-- name: MarkWebhookSuccess :exec
UPDATE webhook_deliveries SET result = 'success', status_code = $2, response_snippet = $3 WHERE id = $1
`

type MarkWebhookSuccessParams struct {
	ID              uuid.UUID `json:"id"`
	StatusCode      *int32    `json:"status_code"`
	ResponseSnippet *string   `json:"response_snippet"`
}

func (q *Queries) MarkWebhookSuccess(ctx context.Context, arg MarkWebhookSuccessParams) error {
	_, err := q.db.Exec(ctx, markWebhookSuccess, arg.ID, arg.StatusCode, arg.ResponseSnippet)
	return err
}

const requeueWebhookDelivery = `-- name: RequeueWebhookDelivery :exec
UPDATE webhook_deliveries SET result = 'pending', next_attempt_at = now(), status_code = NULL, response_snippet = NULL WHERE id = $1
`

func (q *Queries) RequeueWebhookDelivery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, requeueWebhookDelivery, id)
	return err
}
